# Generated by Django 4.1.4 on 2023-01-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aBlog',
            new_name='Blog',
        ),
    ]
